# Generated by Django 4.2 on 2023-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrmCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=50)),
                ('industry_type', models.CharField(choices=[('', 'Select industry type'), ('Computer Industry', 'Computer Industry'), ('Chemical Industries', 'Chemical Industries'), ('Health Services', 'Health Services'), ('Telecommunications Services', 'Telecommunications Services'), ('Textiles: Clothing, Footwear', 'Textiles: Clothing, Footwear')], max_length=50)),
                ('rating', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=150)),
                ('employee', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=150, unique=True)),
                ('since', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Crm Companies',
            },
        ),
    ]
