# Generated by Django 4.2 on 2023-05-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=50)),
                ('logradouro', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=14, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('pais', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=50)),
                ('nomefantasia', models.CharField(blank=True, db_column='NomeFantasia', max_length=50, null=True)),
                ('logradouro', models.CharField(blank=True, db_column='Logradouro', max_length=50, null=True)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, db_column='Complemento', max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=50, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=2, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=30, null=True)),
                ('loja', models.IntegerField(db_column='Loja')),
                ('oficina', models.IntegerField(db_column='Oficina')),
            ],
            options={
                'db_table': 'estabelecimento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=50)),
                ('nomefantasia', models.CharField(blank=True, db_column='NomeFantasia', max_length=50, null=True)),
                ('logradouro', models.CharField(blank=True, db_column='Logradouro', max_length=50, null=True)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, db_column='Complemento', max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=50, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=2, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=30, null=True)),
            ],
            options={
                'db_table': 'fornecedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('ano', models.CharField(blank=True, max_length=50, null=True)),
                ('km', models.CharField(blank=True, max_length=50, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('chassi', models.CharField(blank=True, max_length=50, null=True)),
                ('renavam', models.CharField(blank=True, max_length=50, null=True)),
                ('clienteid', models.ForeignKey(db_column='clienteId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.cliente')),
            ],
            options={
                'db_table': 'moto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motomarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'motomarca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motomodelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('marcaid', models.ForeignKey(db_column='marcaId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.motomarca')),
            ],
            options={
                'db_table': 'motomodelo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=16)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ano', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produtocategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'produtocategoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriminacao', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'servico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacriacao', models.DateTimeField(db_column='dataCriacao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('clienteid', models.ForeignKey(blank=True, db_column='clienteId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.cliente')),
                ('motoid', models.ForeignKey(blank=True, db_column='motoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.moto')),
            ],
            options={
                'db_table': 'venda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendaservico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('servicoid', models.ForeignKey(db_column='servicoId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.servico')),
                ('vendaid', models.ForeignKey(db_column='vendaId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.venda')),
            ],
            options={
                'db_table': 'vendaservico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendaproduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produtoid', models.ForeignKey(db_column='produtoId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.produto')),
                ('vendaid', models.ForeignKey(db_column='vendaId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.venda')),
            ],
            options={
                'db_table': 'vendaproduto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50, unique=True)),
                ('salt', models.CharField(db_column='Salt', max_length=100)),
                ('hash', models.CharField(db_column='Hash', max_length=100)),
                ('idestabelecimento', models.ForeignKey(blank=True, db_column='IdEstabelecimento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.estabelecimento')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProdutoMotomodelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmotomodelo', models.ForeignKey(db_column='idMotoModelo', on_delete=django.db.models.deletion.DO_NOTHING, to='home.motomodelo')),
                ('idproduto', models.ForeignKey(db_column='idProduto', on_delete=django.db.models.deletion.DO_NOTHING, to='home.produto')),
            ],
            options={
                'db_table': 'produto_motomodelo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='idcategoria',
            field=models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.DO_NOTHING, to='home.produtocategoria'),
        ),
        migrations.AddField(
            model_name='moto',
            name='modeloid',
            field=models.ForeignKey(db_column='modeloId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.motomodelo'),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('localizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('qtd_minima', models.IntegerField(blank=True, null=True)),
                ('idestabelecimento', models.ForeignKey(db_column='idEstabelecimento', on_delete=django.db.models.deletion.DO_NOTHING, to='home.estabelecimento')),
                ('idproduto', models.ForeignKey(db_column='idProduto', on_delete=django.db.models.deletion.DO_NOTHING, to='home.produto')),
            ],
            options={
                'db_table': 'estoque',
                'managed': True,
            },
        ),
    ]
